spring.application.name=foodiesapi

#mongodb configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

#aws s3 configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.region=ap-south-1
aws.s3.bucketname=foodiesapi-bucket

jwt.secret.key=8f3d7a9c2b4e6f1a9d0c3e5b7a8f2d4c6e9b1a3c5d7f8e0a2b4c6d8e1f3a5b7==

#razorpay configuration
razorpay_key=${RAZORPAY_KEY}
razorpay_secret=${RAZORPAY_SECRET}

#file upload size
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB